simulation:
  type: sph_box_2d
  initialization_function: jittered
  num_particles: 8192
  gravity: 9.81
  deltaTime: 0.008
  targetDensity: 15000
  pressureMultiplier: 8.0
  viscosity: 60.0
  boundaryThreshold: 0.005
  boundaryForceStrength: 540000.0
render:
  background_field: none
  particle_radius: 6

