simulation:
  type: sph_box_3d
  initialization_function: uniform
  num_particles: 4096
  gravity: 9.81
  deltaTime: 0.008
  collisionDampingFactor: 0.8
  targetDensity: 1000
  pressureMultiplier: 0.8
render:
  background_field: density
  particle_radius: 12
